SELECT CAT.CD_CATEGORIA,CAT.DS_CATEGORIA,
CASE WHEN RESUL.QTIDECHAMADOS IS NULL THEN 0 ELSE RESUL.QTIDECHAMADOS END
FROM MC_CATEGORIA_PROD CAT LEFT OUTER JOIN (SELECT PRO.CD_CATEGORIA, COUNT(SAC.NR_SAC) AS QTIDECHAMADOS
                                                FROM MC_PRODUTO PRO INNER JOIN MC_SGV_SAC SAC
                                                ON (PRO.CD_PRODUTO = SAC.CD_PRODUTO)
                                                GROUP BY PRO.CD_CATEGORIA) RESUL
ON(CAT.CD_CATEGORIA = RESUL.CD_CATEGORIA)
ORDER BY CAT.CD_CATEGORIA;